name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Add build steps here (refer to step 6)

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
    # Add test steps here (refer to step 7)

  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
    # Add deployment steps here (refer to step 8)
